name = "hw-submission-system"
main = "src/worker.js"
compatibility_date = "2025-12-23"

[vars]
ADMIN_PASS = "Mylover10"
GUEST_PASS = "Qwerasdf"
TEACHER_CREDENTIALS = '[{"name":"wang","pass":"teacher123"}]'
DOMAIN = "yourdomain.com"

[bindings]
# D1 binding
[[d1_databases]]
binding = "DB"
database_name = "hw-submission-sys-db"


# KV namespace binding example
[[kv_namespaces]]
binding = "CONFIG_KV"
id = "09bd280fef254b308f830134607699d4"

# If you use Pages site or Assets, configure accordingly
